# CodeRabbit Configuration File
# Visit https://coderabbit.ai/docs for more information

language: "en-US"
early_access: false
reviews:
  profile: "chill"
  request_changes_workflow: false
  high_level_summary: true
  poem: true
  review_status: true
  collapse_walkthrough: false
  auto_review:
    enabled: true
    drafts: false
  tools:
    github-checks:
      enabled: true
      timeout: 90
    ruff:
      enabled: true
    shellcheck:
      enabled: true
    markdownlint:
      enabled: true
    languagetool:
      enabled: true
      enabled_only: false
      level: "default"
chat:
  auto_reply: true
